/*
	NOTE: THIS FILE IS AUTOGENERATED VIA KMAKE
	THIS FILE SHOULD NOT BE EDITED MANUALLY

	List of all image resources(.png, .k) located in the assets/images directory
	Generated at: Sat Sep 03 2022 19:42:54 GMT-0500 (Central Daylight Time)
*/

#pragma once

enum
{
	TEC_IMAGE_RESOURCE_WHITE1X1,
	TEC_IMAGE_RESOURCE_SUBDIR1_MISSING,
	TEC_IMAGE_RESOURCE_SUBDIR1_BOBS_PUNCH,

	TEC_IMAGE_RESOURCES_MAXIMUM_COUNT
}
tec_image_resources_e;

static char const * tec_image_resources_enum_names[] = {
	"TEC_IMAGE_RESOURCE_WHITE1X1",
	"TEC_IMAGE_RESOURCE_SUBDIR1_MISSING",
	"TEC_IMAGE_RESOURCE_SUBDIR1_BOBS_PUNCH",

};

static char const * global_image_resources_paths[] = {
	"assets/images/white1x1.png",
	"assets/images/Subdir1/missing.png",
	"assets/images/Subdir1/bobs/punch.png",
};

